# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VtkUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel

from qt.DrewPlotWidget import DrewPlotWidget
from qt.DrewQlabel import DrewQlabel


class VtkUI(object):
    def setupUi(self, Frame):
        Frame.setObjectName("医学影像勾画软件")
        Frame.resize(697, 558)
        self.project_list = QtWidgets.QListWidget(Frame)
        self.project_list.setGeometry(QtCore.QRect(23, 215, 111, 331))
        self.project_list.setObjectName("project_list")
        self.del_project_button = QtWidgets.QPushButton(Frame)
        self.del_project_button.setGeometry(QtCore.QRect(15, 185, 120, 32))
        self.del_project_button.setObjectName("del_project_button")
        self.add_project_button = QtWidgets.QPushButton(Frame)
        self.add_project_button.setGeometry(QtCore.QRect(15, 155, 120, 32))
        self.add_project_button.setObjectName("add_project_button")
        self.up_drew_graphicsview = PlotWidget(Frame)
        self.up_drew_graphicsview.setGeometry(QtCore.QRect(148, 86, 256, 192))
        self.up_drew_graphicsview.setObjectName("up_drew_graphicsview")

        self.up_drew_qlabe = DrewQlabel(Frame)
        self.up_drew_qlabe.setGeometry(QtCore.QRect(148, 86, 256, 192))

        self.front_drew_graphicsview = PlotWidget(Frame)
        self.front_drew_graphicsview.setGeometry(QtCore.QRect(420, 86, 256, 192))
        self.front_drew_graphicsview.setObjectName("front_drew_graphicsview")

        self.front_drew_qlabe = DrewQlabel(Frame)
        self.front_drew_qlabe.setGeometry(QtCore.QRect(420, 86, 256, 192))

        self.left_drew_graphicsview = PlotWidget(Frame)
        self.left_drew_graphicsview.setGeometry(QtCore.QRect(148, 360, 256, 192))
        self.left_drew_graphicsview.setObjectName("left_drew_graphicsview")

        self.left_drew_qlabe = DrewQlabel(Frame)
        self.left_drew_qlabe.setGeometry(QtCore.QRect(148, 360, 256, 192))

        self.three_drew_frame = QtWidgets.QFrame(Frame)
        self.three_drew_frame.setGeometry(QtCore.QRect(420, 360, 256, 192))
        self.three_drew_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.three_drew_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.three_drew_frame.setObjectName("three_drew_frame")
        self.threeD_change_button = QtWidgets.QPushButton(Frame)
        self.threeD_change_button.setGeometry(QtCore.QRect(414, 288, 110, 32))
        self.threeD_change_button.setObjectName("threeD_change_button")
        self.up_name_label = QtWidgets.QLabel(Frame)
        self.up_name_label.setGeometry(QtCore.QRect(148, 54, 39, 18))
        self.up_name_label.setObjectName("up_name_label")
        self.left_name_label = QtWidgets.QLabel(Frame)
        self.left_name_label.setGeometry(QtCore.QRect(148, 326, 39, 18))
        self.left_name_label.setObjectName("left_name_label")
        self.front_name_label = QtWidgets.QLabel(Frame)
        self.front_name_label.setGeometry(QtCore.QRect(420, 54, 39, 18))
        self.front_name_label.setObjectName("front_name_label")
        self.three_name_label = QtWidgets.QLabel(Frame)
        self.three_name_label.setGeometry(QtCore.QRect(420, 326, 52, 18))
        self.three_name_label.setObjectName("three_name_label")
        self.up_drew_button = QtWidgets.QPushButton(Frame)
        self.up_drew_button.setGeometry(QtCore.QRect(142, 16, 94, 32))
        self.up_drew_button.setObjectName("up_drew_button")
        self.left_drew_button = QtWidgets.QPushButton(Frame)
        self.left_drew_button.setGeometry(QtCore.QRect(142, 288, 94, 32))
        self.left_drew_button.setObjectName("left_drew_button")
        self.front_drew_button = QtWidgets.QPushButton(Frame)
        self.front_drew_button.setGeometry(QtCore.QRect(414, 16, 94, 32))
        self.front_drew_button.setObjectName("front_drew_button")
        self.up_index_spinbox = QtWidgets.QSpinBox(Frame)
        self.up_index_spinbox.setGeometry(QtCore.QRect(340, 34, 61, 21))
        self.up_index_spinbox.setObjectName("up_index_spinbox")
        self.left_index_spinbox = QtWidgets.QSpinBox(Frame)
        self.left_index_spinbox.setGeometry(QtCore.QRect(340, 306, 61, 24))
        self.left_index_spinbox.setObjectName("left_index_spinbox")
        self.front_index_spinbox = QtWidgets.QSpinBox(Frame)
        self.front_index_spinbox.setGeometry(QtCore.QRect(612, 34, 61, 24))
        self.front_index_spinbox.setObjectName("front_index_spinbox")
        self.add_project_name_line = QtWidgets.QLineEdit(Frame)
        self.add_project_name_line.setGeometry(QtCore.QRect(25, 95, 101, 21))
        self.add_project_name_line.setText("")
        self.add_project_name_line.setObjectName("add_project_name_line")
        self.add_project_color_button = QtWidgets.QPushButton(Frame)
        self.add_project_color_button.setGeometry(QtCore.QRect(15, 125, 120, 32))
        self.add_project_color_button.setObjectName("add_project_color_button")
        self.up_clear_button = QtWidgets.QPushButton(Frame)
        self.up_clear_button.setGeometry(QtCore.QRect(238, 32, 94, 32))
        self.up_clear_button.setObjectName("up_clear_button")
        self.left_clear_button = QtWidgets.QPushButton(Frame)
        self.left_clear_button.setGeometry(QtCore.QRect(238, 304, 94, 32))
        self.left_clear_button.setObjectName("left_clear_button")
        self.front_clear_button = QtWidgets.QPushButton(Frame)
        self.front_clear_button.setGeometry(QtCore.QRect(510, 32, 94, 32))
        self.front_clear_button.setObjectName("front_clear_button")

        self.save_button = QtWidgets.QPushButton(Frame)
        self.save_button.setGeometry(QtCore.QRect(12, 60, 121, 32))
        self.save_button.setObjectName("save_button")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.del_project_button.setText(_translate("Frame", "删除绘画项目"))
        self.add_project_button.setText(_translate("Frame", "添加绘画项目"))
        self.threeD_change_button.setText(_translate("Frame", "切换3d视图"))
        self.up_name_label.setText(_translate("Frame", "上视图"))
        self.left_name_label.setText(_translate("Frame", "左视图"))
        self.front_name_label.setText(_translate("Frame", "前视图"))
        self.three_name_label.setText(_translate("Frame", "三维视图"))
        self.up_drew_button.setText(_translate("Frame", "开始绘画"))
        self.left_drew_button.setText(_translate("Frame", "开始绘画"))
        self.front_drew_button.setText(_translate("Frame", "开始绘画"))
        self.add_project_name_line.setPlaceholderText(_translate("Frame", "添加项目名称"))
        self.add_project_color_button.setText(_translate("Frame", "选择项目颜色"))
        self.up_clear_button.setText(_translate("Frame", "清空绘画"))
        self.left_clear_button.setText(_translate("Frame", "清空绘画"))
        self.front_clear_button.setText(_translate("Frame", "清空绘画"))
        self.save_button.setText(_translate("Frame", "保存项目数据"))
from pyqtgraph import PlotWidget
