mvc:
  hiddenmethod:
    filter:
      enabled: true
spring:
  servlet:
    multipart:
      max-request-size: 5GB  # 上传文件总的最大值 默认10MB
      max-file-size: 1GB #单个文件最大值 默认10MB
  datasource:
    username: root
    password: yaokx
    url: jdbc:mysql://localhost:3306/backend?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

mybatis:
  type-aliases-package: com.backend.pojo
  mapper-locations:
    - classpath:/mapper/*.xml